package com.sme.flux.service;

import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;
import java.util.stream.IntStream;

import org.springframework.stereotype.Service;

import com.sme.flux.builder.PojoGenericBuilder;
import com.sme.flux.model.ArticleName;

import reactor.core.publisher.Flux;
import reactor.core.publisher.Mono;

/**
 * Article name service that provides a list of article names in memory.
 */
@Service
public class ArticleNameInMemoryService
{
    private static final int COUNT = 100;
    private static List<ArticleName> ARTICLE_NAMES = new ArrayList<>();

    static
    {
        // CSOFF
        List<ArticleName> collect = IntStream.range(1, COUNT)
                .mapToObj(id -> new PojoGenericBuilder<>(ArticleName::new)
                        .with(ArticleName::setId, id)
                        .with(ArticleName::setArtId, id % 2 == 0 ? 10 : 20)
                        .with(ArticleName::setDescription, "Autogenerated article description " + id)
                        .with(ArticleName::setName, "Autogenerated article name " + id)
                        .with(ArticleName::setLinkFriendlyName, "/en/articlename/" + id)
                        .with(ArticleName::setLangId, id % 2 == 0 ? 1 : 2)
                        .with(ArticleName::setActiveFlg, true)
                        .build())
                .collect(Collectors.toList());
        // CSON

        ARTICLE_NAMES.addAll(collect);
    }

    /**
     * Fetch Flux instance of article names.
     * 
     * @return Returns the Flux instance of list of articles.
     */
    public Flux<ArticleName> findAll()
    {
        return Flux.fromStream(ARTICLE_NAMES.stream());
    }

    /**
     * Fetch Mono of article name by id.
     * 
     * @param id The id of article name;
     * @return Returns Mono of article name by the given id.
     */
    public Mono<ArticleName> findById(long id)
    {
        return Mono.justOrEmpty(ARTICLE_NAMES.stream()
                .filter(a -> a.getId() == id)
                .findFirst());
    }
}
